title: Autodidacter
author: qmzhou
email: qmzhou@github.com
description: > # this means to ignore newlines until "baseurl:"
  Self-learning is an essential ability in today and future world, it is like having a good eyesight among the blinded people.

# social links
twitter_username: qmzhou@AU
github_username:  qmzhou

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
